import 'package:encrypt/encrypt.dart' as encrypt;

class QRCipher {
  // Use a secure, 32-character key. In a production app, consider hiding this in your .env file
  static final _key = encrypt.Key.fromUtf8('my32lengthsupersecretnooneknows1'); 
  static final _iv = encrypt.IV.fromLength(16);
  static final _encrypter = encrypt.Encrypter(encrypt.AES(_key));

  /// Encrypts plain text into a base64 string for the QR code
  static String encryptData(String plainText) {
    final encrypted = _encrypter.encrypt(plainText, iv: _iv);
    // Add a custom prefix so our scanner quickly knows it's an OntarioTechPlus QR code
    return 'OTP_SECURE:${encrypted.base64}';
  }

  /// Decrypts the scanned text. Returns null if invalid or from an external source.
  static String? decryptData(String encryptedText) {
    if (!encryptedText.startsWith('OTP_SECURE:')) {
      return null; // Not generated by our app
    }
    
    try {
      final base64String = encryptedText.replaceFirst('OTP_SECURE:', '');
      final decrypted = _encrypter.decrypt64(base64String, iv: _iv);
      return decrypted;
    } catch (e) {
      return null; // Decryption failed (tampered data or wrong key)
    }
  }
}