import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:ontario_tech_plus/QRcodes/qr_cipher.dart';
import 'package:url_launcher/url_launcher.dart';

class ScanQRPage extends StatefulWidget {
  const ScanQRPage({super.key});

  @override
  State<ScanQRPage> createState() => _ScanQRPageState();
}

class _ScanQRPageState extends State<ScanQRPage> {
  bool _isProcessing = false;

  void _onDetect(BarcodeCapture capture) {
    if (_isProcessing) return;

    final List<Barcode> barcodes = capture.barcodes;
    for (final barcode in barcodes) {
      final rawValue = barcode.rawValue;
      if (rawValue != null) {
        _isProcessing = true;

        // Attempt to decrypt the code
        final decryptedText = QRCipher.decryptData(rawValue);

        if (decryptedText != null) {
          // Valid App QR Code
          _showResultDialog(
            "Success",
            "Decrypted Data: $decryptedText",
            Colors.green,
            decryptedText,
          );
        } else {
          // Invalid or 3rd Party QR Code
          _showResultDialog(
            "Invalid QR Code",
            "This QR code was not generated by Ontario Tech Plus or is corrupted.",
            Colors.red,
            "",
          );
        }
        break; // Process one barcode at a time
      }
    }
  }

  void _showResultDialog(
    String title,
    String message,
    Color color,
    String link,
  ) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        title: Text(title, style: TextStyle(color: color)),
        content: Text(message),
        actions: [
          if (link.isNotEmpty)
            TextButton(
              onPressed: () async {
                final Uri url = Uri.parse(link);
                if (!await launchUrl(url)) {
                  throw Exception('Could not launch $url');
                }
                Future.delayed(const Duration(seconds: 2), () {
                  _isProcessing = false;
                });
              },
              child: const Text('Open'),
            ),
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              // Adding a small delay before allowing the next scan
              Future.delayed(const Duration(seconds: 2), () {
                _isProcessing = false;
              });
            },
            child: const Text('Scan Again'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Scan QR Code")),
      body: MobileScanner(onDetect: _onDetect),
    );
  }
}
